[package]
name = "fe2o3"
version = "0.1.0"
edition = "2024"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[[bin]]
name = "fe2o3"
test = false
bench = false

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0"

